- hosts: server1

  tasks:
  - name: Ensure group admins exists with correct gid
    ansible.builtin.group:
      name: admins
      state: present
      gid: 1001

  - name: Ensure group developers exists with correct gid
    ansible.builtin.group:
      name: developers
      state: present
      gid: 1002

  - name: Create user admin1
    ansible.builtin.user:
      name: admin1
      group: admins
      state: present
      password: "*"

  - name: Create user developer1
    ansible.builtin.user:
      name: developer1
      group: developers
      state: present
      password: "*"

  - name: install dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
